# Generated by Django 3.0.5 on 2021-04-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filenote',
            old_name='handler',
            new_name='advisor',
        ),
    ]
