# Generated by Django 3.0.5 on 2021-04-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0003_auto_20210429_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='lastfollowupmtext',
            new_name='last_follow_up_text',
        ),
    ]
