# Generated by Django 3.0.5 on 2021-04-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0005_hotel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='User_Profile',
        ),
    ]
