# Generated by Django 3.0.5 on 2021-04-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0008_auto_20210430_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
