# Generated by Django 3.2 on 2021-05-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0010_auto_20210501_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
