# Generated by Django 3.2 on 2021-05-03 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0012_alter_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='break_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('login_user', models.CharField(blank=True, max_length=200, null=True)),
                ('start_break', models.CharField(blank=True, max_length=200, null=True)),
                ('stop_break', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
