# Generated by Django 3.2 on 2021-05-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0015_auto_20210503_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='break_times',
            name='date_today',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='advisor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
