# Generated by Django 3.2 on 2021-05-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0016_auto_20210503_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filenote',
            name='date',
            field=models.DateTimeField(verbose_name='%d-%m-%Y %H:%M:%S'),
        ),
    ]
