# Generated by Django 3.2 on 2021-05-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0020_alter_filenote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filenote',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
