# Generated by Django 3.2 on 2021-05-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0023_auto_20210505_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filenote',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2021-05-05 17:54:24'),
        ),
    ]
