# Generated by Django 3.2 on 2021-05-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0030_login_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user_name', models.CharField(max_length=200)),
                ('last_logout', models.DateTimeField(auto_now_add=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
