# Generated by Django 3.2 on 2021-05-07 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0032_remove_loginhistory_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='last_logout',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='login_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
