# Generated by Django 3.2 on 2021-05-07 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('launchers', '0033_auto_20210507_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='action',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='last_logout',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='user_name',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='logout_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='login_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Login_Activity',
        ),
    ]
