# Generated by Django 3.2 on 2021-05-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0034_auto_20210507_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
