# Generated by Django 3.2 on 2021-05-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0037_remove_user_profile_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='office_email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
