# Generated by Django 3.2 on 2021-05-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0038_user_profile_office_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
