# Generated by Django 3.2.6 on 2021-09-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchers', '0044_auto_20210906_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
